# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:hbs
    - run: npm run lint:js
    - run: npm test
      env:
        CI: true
  ember-try:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        try-scenario: [ember-lts-3.12,
                       ember-lts-3.16,
                       ember-release,
                       ember-beta,
                       ember-default-with-jquery,
                       ember-classic]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
      env:
        CI: true
